### PR TITLE
add multiline comments

### PR DESCRIPTION
**Pull request by TheArrowsmith**
See https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-comments

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by TheArrowsmith** [comment]
can we please get a version bump for this?

**Comment by josevalim** [comment]
@TheArrowsmith I have asked publish access.

**Comment by josevalim** [comment]
Done.

**Comment by TheArrowsmith** [comment]
Thanks!

**Pull request merged**
